opensafely-core/repo-template

.github/workflows/main.yml
By default the hadolint action fails at the "info" level, which complains about things like consecutive RUN commands.  This makes it fail at the same level as the pre-commit hook.
=> Update hadolint github action and set failure threshold

scripts/do
`/bin/bash` invokes `3.2.57(1)-release` on macOS, which doesn't support `-v`. Changing the shebang to `/usr/bin/env bash` uses the current environment, which (hopefully) has a more recent version of bash.
Closes #4
=> Change shebang

.flake8
I think we want to extend-exclude, because we also want to exclude the default glob patterns. Of these, the most relevant are `.git` and `__pycache__`. For more, see <https://flake8.pycqa.org/en/stable/user/options.html#cmdoption-flake8-exclude>.
=> Prefer extend-exclude to exclude

pyproject.toml
This uses the relatively new profile feature of isort so we can remove a few lines of config.  Since we added these lines to make black and isort play nicely this seems like an all around win.
=> Use black profile for isort

.pre-commit-config.yaml
pre-commit can set a [default language version](https://pre-commit.com/#top_level-default_language_version), which saves us adding it to every hook.
=> Set a default python version for all pre-commit hooks

requirements.dev.in
[pytest-coverage](https://pypi.org/project/pytest-coverage/) is a fork of pytest-cov and hasn't seen a release since 2015.
=> replace pytest-coverage with pytest-cov

.github/workflows/main.yml
We've done this in several repos now, it tightens the loop for checking tests work and we've found it doesn't really add much to have the checks run as a prerequisite of tests.
=> Remove dependency of tests on checks in CI

README.md, justfile
Some projects use requirements.prod.in to specify dependency specs,
others use pyproject.toml (typically these are pip-installable).  This
allows us to configure which file we want to use in the
requirements-prod target without having to use a conditional in the
upgrade target.
=> Make it easier to use pyproject.toml OR requirements.prod.in

.flake8
This makes our flake8 more explicitly match the black style.
We've only hit E203 in a couple of places but it's good to be consistent.
=> Tweak flake8

justfile
This adds windows support to our justfile.
Note: this does **not** address hashed requirements when dependencies have optional OS-specific sub-depencies (see #52)
=> Windows just support

justfile
The _compile target is the only place we use flags now so this was
unused.
=> Remove $COMPILE, we no longer use it

.pre-commit-config.yaml
This appeases my fussiness.
The original URLs were all lowercase on GitLab, but not on GitHub.
Merely switching the domain works, because GitHub transparently treats
the URLs identically regardless of case. But the canonical URL is listed
in the source as below.
=> Use canonical URLs in `.pre-commit-config`

.github/workflows/auto-merge-dependabot-prs.yml
Use the Org-level workflow for auto-merging Dependabot PRs by default in our repos.
Fixes #68
=> feat: automatically approve and merge dependabot PRs

justfile
This doesn't include the collecstatic piece of the stack since it's Django-specific.
=> Add the assets-* commands to the justfile

.gitignore, pyproject.toml
By default (according to --help as of v22.8.0) black is already ignoring this list of directories:
/(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|venv|\.svn|_build|buck-out|build|dist|__pypackages__)/
We were using --exclude which overwrote this list.  Black supports --extend-exclude which builds upon this list and also makes use of the repos .gitignore [1].  Since we we want both git and black to ignore the files for this repo can drop all black config here.
1: https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore
Fixes: opensafely-core/repo-template#85
=> Remove unnecessary black config

.github/workflows/auto-merge-dependabot-prs.yml
This workflow gives the impression that any Dependabot changes are auto-deployed after being merged, but that's not currently the case. Rather than fixing it, we've decided that we will manually approve all Dependabot PRs, which will then be deployed as soon as we merge them.
=> Remove Dependabot auto-merge function

justfile
While browsing the Just Programmer's Manual section on "[Recipe Parameters](https://just.systems/man/en/chapter_38.html)", I noticed that variables can be passed as arguments to dependencies. For example:
```sh
target := "main"
_build version:
@echo 'Building {{version}}…'
cd {{version}} && make
build: (_build target)
```
Extending the example, what if we wanted to save some typing by adding a `build-main` recipe?
```sh
_build version:
@echo 'Building {{version}}…'
cd {{version}} && make
build-main: (_build 'main')
```
We have a couple of pairs of recipes where we already save some typing: `requirements-prod`, `requirements-dev`, `prodenv`, and `devenv`. However, we do so by duplicating commands. In this PR, we remove some repetition by simplifying recipe parameters, just as we do in …
=> Simplify recipe parameters

.pre-commit-config.yaml, justfile, requirements.dev.in, requirements.dev.txt
Using `ruff format`:
* is much quicker than `black`
* gives largely the same formatting as `black`
* reduces the number of developer dependencies
(This was discussed in the tech team meeting 2024-08-15 and no-one objected to this change.)
=> Switch from `black` to `ruff format`

DEVELOPERS.md
just's installation instructions have improved a LOT since these instructions were written, especially for linux. We can now just link to the just manual page for all the installation instructions for all OS.
=> Update installation instructions for just

.github/dependabot.yml, .github/workflows/update-dependencies.yml, justfile
Dependabot workflows have been broken for a while (e.g. [this run](https://github.com/opensafely-core/repo-template/actions/runs/11447629415)). This seems due to a https://github.com/dependabot/dependabot-core/issues/10631which is now happening on various repos (related to a variety of dependencies).
This replaces the python dependency updates with our custom update-dependencies-action, which updates all dependencies and opens a PR if necessary. We keep dependabot for Github Action updates only.
=> Replace dependabot with update-dependencies-action

.github/workflows/main.yml
Note: this PR is pointed to the `switch-to-uv` branch as we probably do not want to merge into `main` just yet.
We have released [v1.6.1 of setup-action](https://github.com/opensafely-core/setup-action/releases/tag/v1.6.1), which includes an `install-uv` option.
Set this to true in the template, as we assume most python projects would like to use `uv` to manage dependencies.
We take advantage of the caching competencies of astral's setup-uv action for speedier CI runs, by setting `setup-action`'s `cache` param to "uv".
=> Enable `uv` on CI
